// 20 Verified Demo Volunteer Donors across Odisha (Khordha & Bhubaneswar)
export const MOCK_DONORS = [
  {
    id: 101,
    full_name: "Subrat Kumar Jena",
    email: "subrat.jena@demo.pulseconnect.org",
    phone_number: "+91 98610 23411",
    blood_group: "O+",
    locality: "Patia, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3551,
    longitude: 85.8189,
    total_donations: 6,
    last_donation_date: "2026-05-10",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-08-12T10:00:00Z"
  },
  {
    id: 102,
    full_name: "Priyanka Mohapatra",
    email: "priyanka.mohapatra@demo.pulseconnect.org",
    phone_number: "+91 94371 88204",
    blood_group: "O-",
    locality: "Saheed Nagar, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2882,
    longitude: 85.8456,
    total_donations: 4,
    last_donation_date: "2026-04-18",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-09-05T14:30:00Z"
  },
  {
    id: 103,
    full_name: "Soumya Ranjan Das",
    email: "soumya.das@demo.pulseconnect.org",
    phone_number: "+91 97782 54190",
    blood_group: "B+",
    locality: "Chandrasekharpur, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3245,
    longitude: 85.8164,
    total_donations: 8,
    last_donation_date: "2026-06-02",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-07-20T08:15:00Z"
  },
  {
    id: 104,
    full_name: "Lipika Patnaik",
    email: "lipika.patnaik@demo.pulseconnect.org",
    phone_number: "+91 99370 12985",
    blood_group: "A+",
    locality: "Nayapalli, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3012,
    longitude: 85.8234,
    total_donations: 3,
    last_donation_date: "2026-03-22",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-11-12T11:45:00Z"
  },
  {
    id: 105,
    full_name: "Debashis Mishra",
    email: "debashis.mishra@demo.pulseconnect.org",
    phone_number: "+91 98532 77410",
    blood_group: "B-",
    locality: "Jayadev Vihar, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3041,
    longitude: 85.8190,
    total_donations: 5,
    last_donation_date: "2026-05-15",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-10-01T09:20:00Z"
  },
  {
    id: 106,
    full_name: "Ananya Sahoo",
    email: "ananya.sahoo@demo.pulseconnect.org",
    phone_number: "+91 94398 65231",
    blood_group: "AB+",
    locality: "Khandagiri, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2602,
    longitude: 85.7876,
    total_donations: 2,
    last_donation_date: "2026-02-14",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2026-01-08T16:10:00Z"
  },
  {
    id: 107,
    full_name: "Rakesh Kumar Rout",
    email: "rakesh.rout@demo.pulseconnect.org",
    phone_number: "+91 96924 33187",
    blood_group: "A-",
    locality: "Old Town, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2415,
    longitude: 85.8335,
    total_donations: 7,
    last_donation_date: "2026-05-28",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-06-18T13:00:00Z"
  },
  {
    id: 108,
    full_name: "Smaranika Pradhan",
    email: "smaranika.pradhan@demo.pulseconnect.org",
    phone_number: "+91 98614 90123",
    blood_group: "AB-",
    locality: "Rasulgarh, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2974,
    longitude: 85.8643,
    total_donations: 3,
    last_donation_date: "2026-04-05",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-12-04T15:25:00Z"
  },
  {
    id: 109,
    full_name: "Ashish Mohanty",
    email: "ashish.mohanty@demo.pulseconnect.org",
    phone_number: "+91 94372 41560",
    blood_group: "O+",
    locality: "Jatni, Khordha",
    city: "Khordha",
    state: "Odisha",
    latitude: 20.1633,
    longitude: 85.7067,
    total_donations: 9,
    last_donation_date: "2026-06-11",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-05-14T12:00:00Z"
  },
  {
    id: 110,
    full_name: "Biswajit Nayak",
    email: "biswajit.nayak@demo.pulseconnect.org",
    phone_number: "+91 97761 28904",
    blood_group: "B+",
    locality: "Khurda Town, Khordha",
    city: "Khordha",
    state: "Odisha",
    latitude: 20.1812,
    longitude: 85.6214,
    total_donations: 4,
    last_donation_date: "2026-03-30",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-08-29T10:40:00Z"
  },
  {
    id: 111,
    full_name: "Tapasi Barik",
    email: "tapasi.barik@demo.pulseconnect.org",
    phone_number: "+91 99388 56120",
    blood_group: "O-",
    locality: "Mancheswar, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3189,
    longitude: 85.8521,
    total_donations: 5,
    last_donation_date: "2026-05-04",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-07-11T17:30:00Z"
  },
  {
    id: 112,
    full_name: "Pradeep Kumar Behera",
    email: "pradeep.behera@demo.pulseconnect.org",
    phone_number: "+91 98539 10455",
    blood_group: "A+",
    locality: "Baramunda, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2789,
    longitude: 85.7954,
    total_donations: 6,
    last_donation_date: "2026-06-08",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-04-22T08:50:00Z"
  },
  {
    id: 113,
    full_name: "Monali Samantaray",
    email: "monali.samantaray@demo.pulseconnect.org",
    phone_number: "+91 94380 77341",
    blood_group: "B+",
    locality: "Unit-9, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2814,
    longitude: 85.8378,
    total_donations: 3,
    last_donation_date: "2026-04-12",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-11-03T14:15:00Z"
  },
  {
    id: 114,
    full_name: "Satya Narayan Tripathy",
    email: "satya.tripathy@demo.pulseconnect.org",
    phone_number: "+91 96921 68430",
    blood_group: "O+",
    locality: "Sailashree Vihar, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3341,
    longitude: 85.8112,
    total_donations: 11,
    last_donation_date: "2026-05-19",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-03-10T11:20:00Z"
  },
  {
    id: 115,
    full_name: "Madhusmita Senapati",
    email: "madhusmita.senapati@demo.pulseconnect.org",
    phone_number: "+91 98612 35890",
    blood_group: "A-",
    locality: "Ghatikia, Khandagiri, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2645,
    longitude: 85.7721,
    total_donations: 4,
    last_donation_date: "2026-03-15",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-10-19T09:40:00Z"
  },
  {
    id: 116,
    full_name: "Chandan Sekhar Panda",
    email: "chandan.panda@demo.pulseconnect.org",
    phone_number: "+91 94374 81299",
    blood_group: "B-",
    locality: "Kalinga Nagar, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2512,
    longitude: 85.7589,
    total_donations: 5,
    last_donation_date: "2026-05-25",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-09-15T16:00:00Z"
  },
  {
    id: 117,
    full_name: "Sweta Snigdha Ray",
    email: "sweta.ray@demo.pulseconnect.org",
    phone_number: "+91 97775 42318",
    blood_group: "O+",
    locality: "Sundarpada, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2241,
    longitude: 85.8178,
    total_donations: 2,
    last_donation_date: "2026-02-28",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2026-01-20T12:30:00Z"
  },
  {
    id: 118,
    full_name: "Deepak Kumar Sethi",
    email: "deepak.sethi@demo.pulseconnect.org",
    phone_number: "+91 99374 91024",
    blood_group: "AB+",
    locality: "Info City, Patia, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.3589,
    longitude: 85.8115,
    total_donations: 7,
    last_donation_date: "2026-06-01",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-06-05T15:10:00Z"
  },
  {
    id: 119,
    full_name: "Jayashree Biswal",
    email: "jayashree.biswal@demo.pulseconnect.org",
    phone_number: "+91 98533 60719",
    blood_group: "A+",
    locality: "Bhubaneswar Station Road, Khordha",
    city: "Khordha",
    state: "Odisha",
    latitude: 20.1923,
    longitude: 85.6421,
    total_donations: 4,
    last_donation_date: "2026-04-20",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-08-14T11:00:00Z"
  },
  {
    id: 120,
    full_name: "Manas Ranjan Mallick",
    email: "manas.mallick@demo.pulseconnect.org",
    phone_number: "+91 94391 24873",
    blood_group: "O-",
    locality: "Dumuduma, Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    latitude: 20.2489,
    longitude: 85.7923,
    total_donations: 8,
    last_donation_date: "2026-05-30",
    is_available: true,
    is_verified: true,
    role: "donor_acceptor",
    created_at: "2025-05-02T13:45:00Z"
  }
];

// Active Medical Emergencies from Major Hospitals in Bhubaneswar & Khordha
export const MOCK_EMERGENCIES = [
  {
    id: 201,
    patient_name: "Rajeshwar Patnaik",
    blood_group: "B+",
    units_needed: 2,
    component_type: "Whole Blood",
    hospital_name: "AIIMS Bhubaneswar",
    hospital_locality: "Sijua, Patrapada, Bhubaneswar",
    urgency_level: "Immediate",
    contact_person: "Dr. Prasant Rout (ICU Coordinator)",
    contact_phone: "+91 94370 11223",
    status: "Active",
    posted_by_verified_hospital: true,
    created_at: new Date(Date.now() - 24 * 60000).toISOString()
  },
  {
    id: 202,
    patient_name: "Sanghamitra Das",
    blood_group: "O-",
    units_needed: 1,
    component_type: "Whole Blood",
    hospital_name: "Apollo Hospitals Bhubaneswar",
    hospital_locality: "Sainik School Road, Bhubaneswar",
    urgency_level: "Immediate",
    contact_person: "Debendra Das",
    contact_phone: "+91 98611 44556",
    status: "Active",
    posted_by_verified_hospital: true,
    created_at: new Date(Date.now() - 52 * 60000).toISOString()
  },
  {
    id: 203,
    patient_name: "Bikash Kumar Nayak",
    blood_group: "A+",
    units_needed: 3,
    component_type: "Platelets",
    hospital_name: "KIMS Hospital (KIIT Campus)",
    hospital_locality: "Patia, Bhubaneswar",
    urgency_level: "Within 6 Hours",
    contact_person: "Satyajit Nayak",
    contact_phone: "+91 97780 77889",
    status: "Active",
    posted_by_verified_hospital: true,
    created_at: new Date(Date.now() - 110 * 60000).toISOString()
  }
];

export const MOCK_STATS = {
  total_donors: 24,
  active_ready_donors: 20,
  active_emergencies: 3,
  total_lives_saved: 112,
  avg_response_time_minutes: 14,
  golden_hour_success_rate: "94.8%"
};

export const MOCK_TRACKER_DATA = {
  summary: {
    total: 3,
    accepted: 2,
    pending: 1,
    fulfilled: 12
  },
  requests: [
    {
      id: 201,
      patient_name: "Rajeshwar Patnaik",
      blood_group: "B+",
      units_needed: 2,
      component_type: "Whole Blood",
      hospital_name: "AIIMS Bhubaneswar",
      hospital_locality: "Sijua, Patrapada, Bhubaneswar",
      urgency_level: "Immediate",
      contact_person: "Dr. Prasant Rout (ICU Coordinator)",
      contact_phone: "+91 94370 11223",
      status: "Active",
      posted_by_verified_hospital: true,
      created_at: new Date(Date.now() - 24 * 60000).toISOString(),
      dispatched_count: 2,
      accepted_donors: [
        { name: "Soumya Ranjan Das", phone: "+91 97782 54190", eta: "15 mins" }
      ]
    },
    {
      id: 202,
      patient_name: "Sanghamitra Das",
      blood_group: "O-",
      units_needed: 1,
      component_type: "Whole Blood",
      hospital_name: "Apollo Hospitals Bhubaneswar",
      hospital_locality: "Sainik School Road, Bhubaneswar",
      urgency_level: "Immediate",
      contact_person: "Debendra Das",
      contact_phone: "+91 98611 44556",
      status: "Active",
      posted_by_verified_hospital: true,
      created_at: new Date(Date.now() - 52 * 60000).toISOString(),
      dispatched_count: 1,
      accepted_donors: [
        { name: "Priyanka Mohapatra", phone: "+91 94371 88204", eta: "18 mins" }
      ]
    }
  ]
};
